Student Name: Eamon OGairbhith
Student ID:9638296

- The 'as' keyword allows you to invoke functionality from the module using an alias for the module name. For example: np.mean() instead of numpy.mean()
- The from keyword allows you to only import the functionality of interest, for example above we import only the PCA class from the sklearn.decomposition module

In [1]:
import numpy as np
import random as random
import matplotlib.pyplot as plt
from numpy.linalg import eig
from sklearn.decomposition import PCA

As per E-tivity instructions: Use of the matrix class is discouraged, but to allow us to simplify the code slightly, we will use it this week. Its first use will be to store the data that you will perform the PCA transform on. Note that you will likely obtain a higher score if your final version does not use the matrix class.

In [2]:
a_x = 0.05
a_y= 10

In [5]:
data =  np.array([[n*(1+a_x*(random.random()-0.5)),4*n+ a_y*(random.random()-0.5)] for n in range(20)])
data

array([[ 0.        , -2.51622613],
       [ 0.99129236,  8.1547295 ],
       [ 1.99302573,  5.60027896],
       [ 3.02438178, 13.95868729],
       [ 4.0847596 , 16.73643795],
       [ 4.99412896, 16.64001115],
       [ 6.14482034, 27.12293471],
       [ 7.0440443 , 27.87813857],
       [ 7.91781725, 36.90582198],
       [ 9.11217736, 33.18895965],
       [10.23643961, 35.59789662],
       [11.06044339, 42.57199026],
       [11.87895787, 50.34636127],
       [12.69628651, 49.71738007],
       [13.90198554, 58.02424585],
       [14.85748843, 60.92937476],
       [16.06318743, 59.07716676],
       [17.38932104, 70.42645118],
       [17.63226471, 73.33791701],
       [19.17320741, 75.78699978]])

The numpy shape property is very useful to get an insight in the dimensions of your data, for example to check whether the features (in this case 2) or the samples (in this case 20) are in the rows or the columns. The notation used here (with columns containing the features and rows containing separate examples) is the standard for Scikitlearn and many other machine learning algorithms.


In [6]:
data.shape

(20, 2)

In [7]:
print(data)

[[ 0.         -2.51622613]
 [ 0.99129236  8.1547295 ]
 [ 1.99302573  5.60027896]
 [ 3.02438178 13.95868729]
 [ 4.0847596  16.73643795]
 [ 4.99412896 16.64001115]
 [ 6.14482034 27.12293471]
 [ 7.0440443  27.87813857]
 [ 7.91781725 36.90582198]
 [ 9.11217736 33.18895965]
 [10.23643961 35.59789662]
 [11.06044339 42.57199026]
 [11.87895787 50.34636127]
 [12.69628651 49.71738007]
 [13.90198554 58.02424585]
 [14.85748843 60.92937476]
 [16.06318743 59.07716676]
 [17.38932104 70.42645118]
 [17.63226471 73.33791701]
 [19.17320741 75.78699978]]


In [8]:
# calculating the mean of each column
M = np.mean(data.T, axis=1)
print(M)

[ 9.50980148 37.97427786]


In [9]:
# centering the columns by subtracting the column means
C = data - M
print(C)

[[ -9.50980148 -40.49050399]
 [ -8.51850912 -29.81954836]
 [ -7.51677575 -32.3739989 ]
 [ -6.48541971 -24.01559057]
 [ -5.42504188 -21.23783991]
 [ -4.51567252 -21.3342667 ]
 [ -3.36498114 -10.85134315]
 [ -2.46575718 -10.09613929]
 [ -1.59198423  -1.06845588]
 [ -0.39762412  -4.7853182 ]
 [  0.72663813  -2.37638124]
 [  1.55064191   4.5977124 ]
 [  2.36915639  12.37208341]
 [  3.18648503  11.74310221]
 [  4.39218405  20.04996799]
 [  5.34768695  22.9550969 ]
 [  6.55338595  21.1028889 ]
 [  7.87951956  32.45217332]
 [  8.12246323  35.36363915]
 [  9.66340593  37.81272192]]


In [10]:
# calculating the covariance matrix of the centered matrix
V = np.cov(C.T)
print(V)

[[ 34.86628943 139.17564215]
 [139.17564215 564.68364306]]


In [11]:
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)

[[-0.97089193 -0.23951798]
 [ 0.23951798 -0.97089193]]
[5.31810233e-01 5.99018122e+02]


In [12]:
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[-4.65214238e-01  4.15896720e+01]
 [ 1.12823376e+00  3.09918949e+01]
 [-4.56177928e-01  3.32320572e+01]
 [ 5.44475895e-01  2.48699177e+01]
 [ 1.80284856e-01  2.19190424e+01]
 [-7.25710468e-01  2.17948521e+01]
 [ 6.67941232e-01  1.13414550e+01]
 [-2.42231508e-02  1.03928533e+01]
 [ 1.28973025e+00  1.41866404e+00]
 [-7.60119701e-01  4.74126495e+00]
 [-1.27467313e+00  2.13316647e+00]
 [-4.04270925e-01 -4.83528848e+00]
 [ 6.63141613e-01 -1.25794115e+01]
 [-2.81048473e-01 -1.21645036e+01]
 [ 5.37991792e-01 -2.05183591e+01]
 [ 3.06132351e-01 -2.35677855e+01]
 [-1.30810819e+00 -2.20582783e+01]
 [ 1.22717068e-01 -3.33948398e+01]
 [ 5.84193436e-01 -3.62797478e+01]
 [-3.25296035e-01 -3.90266260e+01]]


In [13]:
class testPCA():
    
    def __init__(self, num_comp):
        """ Setting the number of components we want to return
        """
        self.n_components = num_comp
        
    def __str__(self):
        """
        provide access to the tensor's internal matrix
        """
        #Taken from Brian's methodology
        return str(self.np_matrix)
        
    def fit(self, data):
        """
        The fit method calculates the eigenvectors and eigenvalues of the data in matrix using the forumla outlined above
           
        """   
        self.np_matrix = data
        self.shape = self.np_matrix.shape
        #Caclulate the mean
        self.np_mean = np.mean(self.np_matrix.T, axis=1)
        #Centre the data
        self.np_centre = self.np_matrix - self.np_mean
        #Calculate covariance
        self.np_cov = np.cov(self.np_centre.T)
        #Calculate eigenvectors and eigenvalues
        self.np_eigenvalues, self.np_eigenvectors = eig(self.np_cov)
        
        #Sort eigenvectors by eigenvalues descending
        #Sort the order for the eigenvalues
        array_sort = np.argsort(self.np_eigenvalues)
        #Sort the Eigen values and then sort the eigen vectors based on how the eigen values were sorted
        self.np_eigenvalues.sort()
        self.np_eigenvectors = self.np_eigenvectors[array_sort]
        #Reverse both to have them in descending order
        self.np_eigenvalues = self.np_eigenvalues[::-1]
        self.np_eigenvectors = self.np_eigenvectors[::-1] 
        #Transpose the eigenvectors as linalg returns the vectors in columns
        self.np_eigenvectors = self.np_eigenvectors.T[array_sort]
        #Reduce to number of components specified
        self.np_eigenvalues = self.np_eigenvalues[:self.n_components]
        self.np_eigenvectors = self.np_eigenvectors[:self.n_components]
        
        #Square each value so that magnitude and not sign is taken into account when ordering as per Cormac's advice
        
        sorted_eigen_values_indexes = np.square(values).argsort()[::-1]
        sorted_eigen_values = values[sorted_eigen_values_indexes]
        sorted_eigen_vectors = vectors[:, sorted_eigen_values_indexes]
        self.eigen_values = sorted_eigen_values[:self.n_components]
        self.eigen_vectors = sorted_eigen_vectors.T[:, :self.n_components]
        
        return self.np_eigenvalues, self.np_eigenvectors
    
    def transform(self, data):
        """
        A transform function to transform the data using results from fit.
        """
        #Calculate the projection
        data = data - self.np_mean
        #self.np_projection = self.np_eigenvectors.dot(data.T)
        self.np_projection = self.np_eigenvectors.T.dot(self.np_cov.T)
        
        #return the projection
        return self.np_projection.T
    
    def inverse_transform(self, data):
        """
        Return the Original Data Reduced with Mean added
        """
        return np.dot(self.np_eigenvectors.T, self.np_projection).T + self.np_mean

        
#A = testPCA(2)
#A.fit(data)
#print (A.np_eigenvalues)
#print (A.np_eigenvectors)
#print (A.transform(data))
#A.transform(data)
#print (A.inverse_transform(data))

A = testPCA(2)
A.fit(data)
print(f"The Eigenvalues of the data are {A.np_eigenvalues}\n")
print(f"The Eigenvectors of the data are\n{A.np_eigenvectors}\n")
print(f"The transform of the data is\n{A.transform(data)}\n")
print(f"The inverse transform of the data is\n{A.inverse_transform(data)}\n")

The Eigenvalues of the data are [5.99018122e+02 5.31810233e-01]

The Eigenvectors of the data are
[[ 0.23951798 -0.97089193]
 [-0.97089193 -0.23951798]]

The transform of the data is
[[-126.77340439  -67.18646771]
 [-514.91172255 -270.37639335]]

The inverse transform of the data is
[[ 44.37609091 177.14992   ]
 [148.68544363 602.65792092]]



In [18]:
#now calculate using scikit

pca = PCA(n_components=2)
pca.fit(data)

print("Scikitlearn PCA Eigen vectors\n")
print(pca.components_)
print("\nScikitlearn PCA Eigen values\n")
print(pca.explained_variance_)
print("\nScikitlearn PCA Variance Ratio\n")
print(pca.explained_variance_ratio_)
print("\nTransform:\n")
print(pca.transform(data))
pca.transform(data)
print("\nInverse Transform:\n")
print(pca.inverse_transform(data))

Scikitlearn PCA Eigen vectors

[[-0.23951798 -0.97089193]
 [ 0.97089193 -0.23951798]]

Scikitlearn PCA Eigen values

[5.99018122e+02 5.31810233e-01]

Scikitlearn PCA Variance Ratio

[9.99112984e-01 8.87015750e-04]

Transform:

[[ 4.15896720e+01  4.65214238e-01]
 [ 3.09918949e+01 -1.12823376e+00]
 [ 3.32320572e+01  4.56177928e-01]
 [ 2.48699177e+01 -5.44475895e-01]
 [ 2.19190424e+01 -1.80284856e-01]
 [ 2.17948521e+01  7.25710468e-01]
 [ 1.13414550e+01 -6.67941232e-01]
 [ 1.03928533e+01  2.42231508e-02]
 [ 1.41866404e+00 -1.28973025e+00]
 [ 4.74126495e+00  7.60119701e-01]
 [ 2.13316647e+00  1.27467313e+00]
 [-4.83528848e+00  4.04270925e-01]
 [-1.25794115e+01 -6.63141613e-01]
 [-1.21645036e+01  2.81048473e-01]
 [-2.05183591e+01 -5.37991792e-01]
 [-2.35677855e+01 -3.06132351e-01]
 [-2.20582783e+01  1.30810819e+00]
 [-3.33948398e+01 -1.22717068e-01]
 [-3.62797478e+01 -5.84193436e-01]
 [-3.90266260e+01  3.25296035e-01]]

Inverse Transform:

[[ 7.06681784 38.57695926]
 [17.18973019 35.0586357