Student Name: Fergus Mc Hale
Student ID: 18203485

- References
- https://stackoverflow.com/questions/36771525/python-pca-projection-into-lower-dimensional-space
- http://nasseralkmim.github.io/notes/2017/03/20/linear-algebra-change-of-basis-explained-using-python/
- http://people.cs.pitt.edu/~iyad/PCA.pdf
- http://people.duke.edu/~ccc14/sta-663-2016/09_PCA.html#Change-of-basis-via-PCA
- https://github.com/minsuk-heo/python_tutorial/blob/master/data_science/pca/PCA.ipynb
- https://plot.ly/ipython-notebooks/principal-component-analysis/
- https://stackoverflow.com/questions/13224362/principal-component-analysis-pca-in-python
- https://github.com/echen/principal-components-analysis/blob/master/pca.py
- https://medium.com/district-data-labs/principal-component-analysis-with-python-4962cd026465
- https://alyssaq.github.io/2015/understanding-eigenvectors-and-eigenvalues-visually/
- https://community.esri.com/blogs/dan_patterson/2014/11/29/using-numpy-linalg-to-replicate-matrix-operations-reinventing-the-wheel
- https://stackoverflow.com/questions/23838056/what-is-the-difference-between-transform-and-fit-transform-in-sklearn
- https://www.kaggle.com/nirajvermafcb/principal-component-analysis-explained

- Making use of Numpy, write a Python class to apply the PCA transform to the provided (see Notebook) data set. Compare the output of your implementation to the PCA functionality provided by the Scikitlearn module.

- Create a 'fit' method that calculates the eigen vectors and eigen values of your dataset. Compare your results to the output of Scikitlearn's fit method and document your findings as a comment (use markdown) directly under the cell with your PCA class.
- Use the Scikitlean's PCA class with n_components=2 and n_components=1 and observe the differences. In the cell directly below, comment on what you have observed.
- Add a property to your class and initialise this property in a suitable fashion to allow you to choose the number of principal components similar to the Scikitlearn PCA class.
- Store those results from your fit method that are required to transform the data set, in suitable class properties.
- Create a 'transform' method to perform the PCA data transformation on your data set using the parameters obtained using your 'fit' method.
 

- N.B.:

- Limit your code to the aspects explicitly listed. 
- Use the Jupyter Notebook provided in the repository for week 5. This notebook contains the data that needs to be transformed.
- The required modules have already been imported for you. You should not import any other modules.
- If you find creating a class with this functionality daunting, please start by creating normal functions in your notebook. If time permits, you can then change to use of a class later. 
 

- HINTS:

- Numpy.mean() will 'flatten' your tensor by default. To obtain the mean along a given axis, you may use the axis parameter.

- Numpy.cov() assumes by default that data is presented with one observation per column. This can be changed using the rowvar parameter. 

- A Numpy.matrix is a convenient way of performing the matrix operations required for PCA whilst retaining a matrix/vector like structure. Use of this class is discouraged, but would form a good starting point for tackling this week's challenge. Once you have the code working with the matrix class, changing to arrays is relatively straight forward.

- You can use Scikitlearn as follows to check the Eigen vectors that you have found with your 'fit' mehod:

- pca = PCA(n_components=2)
- pca.fit(data)
- print(pca.components_)

- You can use Scikitlearn to obtain 
- GIT push your implementation and post your manual calculations to E-tivity 5: Linear Algebra in Numpy and Beyond and provide the name of your branch.

- Respond (Complete by Wednesday Week 6)

- Respond to a post of one of your peers with a respectful and in-depth assessment of the implementation with a view to pointing out potential improvements or sound alternative solutions.

- Reflect (Complete by Saturday Week 6)

- With your code (containing any corrections you have made based on your peers’ feedback), do the following:

- For the case where n_components = 1, compare the resulting dataset of your transform method with the resulting dataset from Scikitlearn’s transform method by plotting the points on an XY plot. If there are any differences, explain these in a comment directly under the cell with your plot.
 - For the case where n_components = 1, compare the dataset resulting from your transform method with the original dataset by plotting the points on an XY plot. Comment on the differences between original and transformed data in the cell directly below your plot. In your comment, explain why and how PCA can be used for dimensionality reduction
 
- HINTS:

- You can use Scitkitlean as follows to calculate the new values of the data points in the original dataset when you reduce the dimensions of the data (from 2) to 1: 
- pca = PCA(n_components=1)
- pca.fit(data)
- data_pca = pca.transform(data)
- data_reduced = pca.inverse_transform(data_pca)

- You can use plots to compare the values in your original dataset with the dataset with reduced dimensionality:
- plt.plot(data[:,0], data[:,1], 'or')
- plt.plot(data_reduced[:,0], data_reduced[:,1],'xb')
 - plt.show()

- You can use your own PCA results to calculate the new values of the data points int the original dataset when you reduce the dimensions of the data (from 2) to 1:
- reduced = np.dot(features[:,0],red_highvar.T)+mean.T

- with:

- reduced: a 2x20 matrix of the new values of the dataset with dimensionality reduction applied
- features[:,0]: the 2x1 matrix (or column vector) which contains the Eigen vector associated with the highest variance
- red_highvar: a 20x1 matrix containing the reduced dataset which is the output of your transform method with n_components set to 1. 
- mean: a 1x2 matrix of the per-column mean values of your original data
- T: the transform operator as provided by Numpy

- The 'as' keyword allows you to invoke functionality from the module using an alias for the module name. For example: np.mean() instead of numpy.mean()
- The from keyword allows you to only import the functionality of interest, for example above we import only the PCA class from the sklearn.decomposition module
- As per E-tivity instructions: Use of the matrix class is discouraged, but to allow us to simplify the code slightly, we will use it this week. 
- Its first use will be to store the data that you will perform the PCA transform on. Note that you will likely obtain a higher score if your final version does not use the matrix class.
- The numpy shape property is very useful to get an insight in the dimensions of your data, for example to check whether the features (in this case 2) or the samples (in this case 20) are in the rows or the columns. The notation used here (with columns containing the features and rows containing separate examples) is the standard for Scikitlearn and many other machine learning algorithms.
- data.shape

2. Use the Scikitlean's PCA class with n_components=2 and n_components=1 and observe the differences. In the cell directly below, comment on what you have observed

In [200]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? Y


 - PCA Implementation

In [201]:
import numpy as np
import random as rand
import matplotlib.pyplot as plt
from numpy.linalg import eig
from sklearn.decomposition import PCA

a_x = 0.05
a_y= 10
data =  np.array([[n*(1+a_x*(rand.random()-0.5)),4*n+ a_y*(rand.random()-0.5)] for n in range(20)])

class pca:
    
    def __init__(self,n_components):
        self.n_components = n_components
        self.eigenvalues = None
        self.eigenvectors = None

    def fit(self, data):
        """Given an array finds the eigenvalues and eigenvectors
            Args:
            data (array) The dataset that has been supplied
            Returns: eigenvectors, eigenvalues (array) The result of the operation performed on the dataset
            """
        self.data = data
        # calculate mean matrix
        self.mean_matrix = np.mean(self.data, axis=0)
        # center the data
        self.centered_data = data - self.mean_matrix
        # get covariance
        self.covariance_matrix = np.cov(self.centered_data, rowvar=False)
        # get eigen vectors and values
        self.eigenvalues, self.eigenvectors = eig(self.covariance_matrix)
        # get the highest eigen value
        index = self.eigenvalues.argsort()[::-1] 
        sorted_eigen_values = self.eigenvalues[index]
        sorted_eigen_vectors = self.eigenvectors.T[index]
        # set components based on eigenvectors
        self.eigenvalues = sorted_eigen_values[:self.n_components] 
        self.eigenvectors = sorted_eigen_vectors[:self.n_components]
        self.components_ = self.eigenvectors
        # return tuple of eigenvalues and eigenvectors
        return self.eigenvalues, self.eigenvectors
    
    def transform(self, data):
        """Given data selects an eigenvector returns the transform 
            Args:
            data (array) The dataset that has been supplied
            Returns: transformed result ()
           """
        centered_data = data - self.mean_matrix
        self.projection = np.dot(centered_data, self.eigenvectors.T)
        return self.projection.T
    
    def inverse_transform(self):
        """find the inverse of the transform"""
        return np.dot(self.eigenvectors.T, self.projection).T + self.np_mean_matrix

PCA is used for dimension reduction to allow the key points of the data to be used.
It is used to give a better perspective on the data.
It allows for better visualisation of the dataset.
It is used to handle data that deals with chaos to find the key points.

In [202]:
print("PCA Implementation One")     
implementated_pca_one = pca(1)
print("Fit")
implementated_pca_one.fit(data)
print(implementated_pca_one.eigenvalues)
print(implementated_pca_one.components_)
print("Transform")
pca_implementation_data_reduced = implementated_pca_one.transform(data)
print(pca_implementation_data_reduced)


print("Scikitlean One")
pca_one = PCA(1)
print("Fit")
scikit_learn_fit = pca_one.fit(data)
print(pca_one.explained_variance_)
print(pca_one.components_)
print("Transform")
scikitlearn_data_reduced = pca_one.transform(data)
print(scikitlearn_data_reduced)

PCA Implementation One
Fit
[580.69277896]
[[-0.24273727 -0.97009207]]
Transform
[[ 39.14062143  36.41084161  31.06439491  24.30527068  23.2736251
   14.94364796  15.21892008  13.90161633   2.81786378   3.3636101
   -6.70310666  -3.33403864 -13.08048815 -14.8742825  -15.59781359
  -24.03828187 -22.46314595 -32.70324698 -35.38071471 -36.26529293]]
Scikitlean One
Fit
[580.69277896]
[[-0.24273727 -0.97009207]]
Transform
[[ 39.14062143]
 [ 36.41084161]
 [ 31.06439491]
 [ 24.30527068]
 [ 23.2736251 ]
 [ 14.94364796]
 [ 15.21892008]
 [ 13.90161633]
 [  2.81786378]
 [  3.3636101 ]
 [ -6.70310666]
 [ -3.33403864]
 [-13.08048815]
 [-14.8742825 ]
 [-15.59781359]
 [-24.03828187]
 [-22.46314595]
 [-32.70324698]
 [-35.38071471]
 [-36.26529293]]


For N_Components = 1
The values of the fit method are the same apart from the polarity of being negative
My Implementation
[[-0.23511795 -0.97196685]]
Scikit learn approach
[[0.23511795 0.97196685]]
The same can also be siad for the transform method where their polarity is negative also (alignment)
My Implementation
[[ 37.54350578  39.97047885  28.60351434  26.85617454  24.20843962
   21.76131034  10.68244962  12.86398836   6.94300844   1.96738381
   -2.88759418  -1.16300718 -12.96133938  -9.91175687 -20.38660606
  -25.23744263 -28.25451011 -34.14991522 -33.69197655 -42.7561055 ]]
Sci Kit learn approach
[[-37.54350578]
 [-39.97047885]
 [-28.60351434]
 [-26.85617454]
 [-24.20843962]
 [-21.76131034]
 [-10.68244962]
 [-12.86398836]
 [ -6.94300844]
 [ -1.96738381]
 [  2.88759418]
 [  1.16300718]
 [ 12.96133938]
 [  9.91175687]
 [ 20.38660606]
 [ 25.23744263]
 [ 28.25451011]
 [ 34.14991522]
 [ 33.69197655]
 [ 42.7561055 ]]

In [203]:
print("PCA Implementation Two")     
implementated_pca_two = pca(2)
print("Fit")
implementated_pca_two.fit(data)
print(implementated_pca_two.eigenvalues)
print(implementated_pca_two.components_)
print("Transform")
pca_data_reduced = implementated_pca_two.transform(data)
print(pca_data_reduced)

print("Scikitlean Two")
pca_two = PCA(2)
print("Fit")
pca_two.fit(data)
print(pca_two.explained_variance_)
print(pca_two.components_)
print("Transform")
scikitlearn_data_reduced = pca_two.transform(data)
print(scikitlearn_data_reduced)

PCA Implementation Two
Fit
[5.80692779e+02 4.88238026e-01]
[[-0.24273727 -0.97009207]
 [-0.97009207  0.24273727]]
Transform
[[ 3.91406214e+01  3.64108416e+01  3.10643949e+01  2.43052707e+01
   2.32736251e+01  1.49436480e+01  1.52189201e+01  1.39016163e+01
   2.81786378e+00  3.36361010e+00 -6.70310666e+00 -3.33403864e+00
  -1.30804882e+01 -1.48742825e+01 -1.55978136e+01 -2.40382819e+01
  -2.24631459e+01 -3.27032470e+01 -3.53807147e+01 -3.62652929e+01]
 [-3.25834317e-02 -3.93729811e-01 -1.02130143e-01  5.37276075e-01
  -1.56132756e-01  9.75602766e-01 -1.86357249e-01 -7.81074189e-01
   9.73647404e-01 -4.85356929e-01  1.22036425e+00 -9.87984157e-01
   4.98237321e-01  3.99539101e-01 -1.06087363e+00  2.51077888e-01
  -9.47614713e-01  8.26062324e-01  6.10836276e-02 -6.09053756e-01]]
Scikitlean Two
Fit
[5.80692779e+02 4.88238026e-01]
[[-0.24273727 -0.97009207]
 [-0.97009207  0.24273727]]
Transform
[[ 3.91406214e+01 -3.25834317e-02]
 [ 3.64108416e+01 -3.93729811e-01]
 [ 3.10643949e+01 -1.021301

For N_Components = 2 the values are the same with the Fit Method
My approach
[[-0.23511795 -0.97196685]
 [-0.97196685  0.23511795]]
Scikit learn approach
[[ 0.23511795  0.97196685]
 [ 0.97196685 -0.23511795]]
The is a polarity difference also present on this set for components
The transform method is also have the same values with polarity is different
My approach
[[ 37.54350578  39.97047885  28.60351434  26.85617454  24.20843962
   21.76131034  10.68244962  12.86398836   6.94300844   1.96738381
   -2.88759418  -1.16300718 -12.96133938  -9.91175687 -20.38660606
  -25.23744263 -28.25451011 -34.14991522 -33.69197655 -42.7561055 ]
 [  0.78330707  -0.84418125   0.87355628   0.23769193  -0.1722061
   -0.63099773   0.99759389  -0.39021     -0.07995347   0.25238552
    0.44958417  -1.32644131   0.39436445  -1.37774806   0.33358567
    0.37628857  -0.16681746   0.3023576   -0.23319982   0.22104004]]
Scikit learn
[[-37.54350578  -0.78330707]
 [-39.97047885   0.84418125]
 [-28.60351434  -0.87355628]
 [-26.85617454  -0.23769193]
 [-24.20843962   0.1722061 ]
 [-21.76131034   0.63099773]
 [-10.68244962  -0.99759389]
 [-12.86398836   0.39021   ]
 [ -6.94300844   0.07995347]
 [ -1.96738381  -0.25238552]
 [  2.88759418  -0.44958417]
 [  1.16300718   1.32644131]
 [ 12.96133938  -0.39436445]
 [  9.91175687   1.37774806]
 [ 20.38660606  -0.33358567]
 [ 25.23744263  -0.37628857]
 [ 28.25451011   0.16681746]
 [ 34.14991522  -0.3023576 ]
 [ 33.69197655   0.23319982]
 [ 42.7561055   -0.22104004]]

Values are correct just cannot graph it due to implemented array being out of alignment.